In [21]:
from numpy import random
l = (3,)
m = dict([(_, random.randint(4)) for _ in range(20)])
from operator import itemgetter
import operator
f = operator.itemgetter(*l)
%timeit f(m)
%timeit [m[_] for _ in l]  # list comprehension
%timeit list(map(m.__getitem__, l))
%timeit list(m[_] for _ in l)  # a generator expression passed to a list constructor.
%timeit list(map(m.get, l))
%timeit list(map(lambda _: m[_], l))

95.7 ns ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


TypeError: 'int' object is not iterable

In [20]:
m

(((3,),),
 {0: 0,
  1: 3,
  2: 0,
  3: 2,
  4: 0,
  5: 1,
  6: 1,
  7: 0,
  8: 0,
  9: 2,
  10: 2,
  11: 0,
  12: 1,
  13: 3,
  14: 0,
  15: 3,
  16: 1,
  17: 0,
  18: 0,
  19: 2})

In [15]:
f(m), list(itemgetter(*l)(m)), [m[_] for _ in l], list(map(m.__getitem__, l)), list(m[_] for _ in l), list(map(m.get, l)), list(map(lambda _: m[_], l))

((3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3),
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3],
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3],
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3],
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3],
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3],
 [3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3])

In [1]:
_code_map = {"red": 0, "green": 1, "blue": 2}
_print_map = {"red": "🔴", "green": "✅", "blue": "🔵"}
_rev_code_map = {value: key for key, value in _code_map.items()}

color_mapping = \
    {
        fr_code:
            {
                to: _rev_code_map[(to_code-fr_code) % 3]
                for to, to_code in _code_map.items()
            }
        for fr, fr_code in _code_map.items()
    }

In [2]:
color_mapping

{0: {'red': 'red', 'green': 'green', 'blue': 'blue'},
 1: {'red': 'blue', 'green': 'red', 'blue': 'green'},
 2: {'red': 'green', 'green': 'blue', 'blue': 'red'}}

In [76]:
%time
l = []
k = [0,1,0]
for i in k: l.append(i)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs


In [85]:
%time
l = []
k = [0,1,0]
l += k

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs


In [89]:
import numpy as np

In [178]:
vectors = [np.array(range(37 * 3)) for i in range(1000)]
%time
vects = []
for vect in vectors:
    vects.append(vect)
v = np.array(vects)
vJ

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 7.15 µs


array([[  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       ...,
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110]])

In [184]:
vectors = [np.array(range(37 * 3)) for i in range(1000)]
%time
v = np.array(vectors[0])
for vect in vectors[1:]:
    v = np.vstack([v, vect])
v

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs


array([[  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       ...,
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110],
       [  0,   1,   2, ..., 108, 109, 110]])

In [186]:
from collections import deque
dq = deque([123, 456])

In [195]:
%time
dq = deque([123, 456])
dq.popleft()

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.96 µs


123

In [198]:
%time
l = [123, 456]
l.pop(0)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.15 µs


123

In [200]:
np.array([123,456])[[0]]

array([123])